config/routes.rb
Rails.application.routes.draw do
# 会員用1です。こんな世界にしてみたい。
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

# ゲストログイン専用
  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

# 検索機能
  get "search" => "searches#search"

# 会員用2
scope module: :public do
  root :to =>"homes#top"
  get "about"=>"homes#about"

  resources :ores, only: [:index,:show,:edit]

  get 'customers/my_page' =>"customers#show"
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw'

  post 'rankings/confirm' => 'rankings#confirm'
  get 'rankings/complete' => 'rankings#complete'
  get 'rankings/bookmark' => 'rankings#bookmark'
  get 'rankings/recommend' => 'rankings#recommend'

  resources :rankings, only: [:new,:create,:index,:show] do
    resource :favorites, only: [:create, :destroy]
    resources :stone_comments, only: [:create, :destroy]
  end

  resources :decorations, only: [:index,:edit,:create,:destroy,:update]
end

#管理者専用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  get "admin" => 'admin/homes#top'

  namespace :admin do
    resources :ores

    resources :genres, only: [:index,:create,:edit,:update,:destroy]

    resources :customers, only: [:index,:show,:edit,:update]

    resources :rankings, only: [:show,:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :rankings, dependent: :destroy
    has_many :decorations, dependent: :destroy
    has_many :stone_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_one_attached :image

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/} #カタカナのみ
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/} #カタカナのみ
  validates :postal_code, presence: true, length: { is: 7 }, numericality: {only_integer: true} #8文字と整数のみ
  validates :address, presence: true
  validates :telephone_number, presence: true, length: { is: 11 }, uniqueness: true, numericality: {only_integer: true} #11文字と整数のみ、重複チェック

  #名前をフルネームで記述できるように
  def full_name
    self.last_name + "" + self.first_name
  end

  #名前かなをフルネームで記述できるように
  def full_name_kana
    last_name_kana + first_name_kana
  end

  # ユーザー用の画像を表示できるように
  def get_image(width, height)
    image.attached?
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/koubutuuser.jpg')
      image.attach(io: File.open(file_path),filename: 'gensekitati', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end


  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.last_name = "user"
      customer.first_name = "guest"
      customer.last_name_kana = "taiki"
      customer.first_name_kana = "sonoyama"
      customer.postal_code = "338"
      customer.address = "saitama"
      customer.telephone_number = "048"
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  # adminの管理者権限
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
    @ranking = Ranking.first
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :password, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">

  <h1 class="teo mt-3">
    <%= @customer.full_name %>さんの
    <strong>会員情報編集</strong>
  </h1>

  <div class="row">

  </div>

  <!--会員情報編集のテーブル-->
  <div class='row'>
    <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
      <table class="havyarms zurasi">

        <tr class="form-group">
          <th class="atora2 kairi2 text-white">会員ID</th>
          <td class="kairi2">
            <%= @customer.id %>
          </td>
          <td class="kairi2"></td>
        </tr>

        <tr class="form-group">
          <th class="atora2 kairi2 text-white">
            <%= f.label :"氏名"%>
          </th>

          <td class="kairi2">
            <%= f.text_field :last_name, autofocus: true, placeholder:"令和" %>
          </td>

          <td class="kairi2">
            <%= f.text_field :first_name, placeholder:"道子" %>
          </td>
        </tr>

        <tr class="form-group">
          <th class="atora2 kairi2 text-white">
            <%= f.label :"フリガナ"%>
          </th>

          <td class="kairi2">
            <%= f.text_field :last_name_kana, placeholder:"レイワ" %>
          </td>

          <td class="kairi2">
            <%= f.text_field :first_name_kana, placeholder:"ミチコ" %>
          </td>
        </tr>

        <tr class="form-group">
          <th class="atora2 kairi2 text-white">
            <%= f.label :"郵便番号"%>
          </th>

          <td class="kairi2">
            <%= f.text_field :postal_code, placeholder:"0000000" %>
          </td>
          <td class="kairi2"></td>
        </tr>

        <tr class="form-group">
          <th class="atora2 kairi2 text-white">
            <%= f.label :"住所"%>
          </th>

          <td class="kairi2">
            <%= f.text_field :address, placeholder:"東京都渋谷区代々木神園町0-0" %>
          </td>
          <td class="kairi2"></td>
        </tr>

        <tr class="form-group">
          <th class="atora2 kairi2 text-white">
            <%= f.label :"電話番号"%>
          </th>

          <td class="kairi2">
            <%= f.text_field :telephone_number, placeholder:"0000000000" %>
          </td>
          <td class="kairi2"></td>
        </tr>

        <tr class="form-group">
          <th class="atora2 kairi2 text-white">
            <%= f.label :"メールアドレス"%>
          </th>

          <td class="kairi2">
            <%= f.email_field :email, placeholder:"sample@example.com" %>
          </td>
          <td class="kairi2"></td>
        </tr>

        <tr class="form-group">
          <th class="atora2 kairi2 text-white">
            <%= f.label :"会員ステータス"%>
          </th>

          <td class="kairi2">
            <%= f.radio_button :is_deleted, :false %>
              <%= f.label :is_deleted, "有効" %>
            <%= f.radio_button :is_deleted, :true %>
              <%= f.label :is_deleted, "退会" %>
          </td>
          <td class="kairi2"></td>
        </tr>

      </table>

      <div class="tyuubu mt-3">
        <%= f.submit '変更を保存', class:'btn btn-success' %>
      </div>
    <% end %>
  </div>

</div>

app/views/admin/customers/index.html.erb
<div class="container">

  <h1 class="teo mt-3">会員一覧</h1>

  <!--会員のテーブル-->
  <div class="row">
    <div class="col-md-8 offset-md-1 pt-4">
      <table class='table table-bordered border-dark text-center'>

        <thead class="hikarian text-white">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <!--繰り返し処理-->
        <% @customers.each do |customer| %>
          <tbody class="haku">
            <tr>
              <td>
                <%= customer.id %>
              </td>

              <td>
                <%= link_to customer.full_name , admin_customer_path(customer.id) %>
              </td>

              <td>
                <%= customer.email %>
              </td>

              <% if customer.is_deleted == false %>
                <td class="text-success font-weight-bold">
                  有効
                </td>
              <% else %>
                <td class="text-secondary font-weight-bold">
                  退会
                </td>
              <% end %>
            </tr>
          </tbody>
        <% end %>

      </table>
    </div>
  </div>

</div>

app/views/admin/customers/show.html.erb
<div class="container">

  <h1 class="teo mt-4">
    <%= @customer.full_name %>さんの
    <strong>会員詳細</strong>
  </h1>

  <!--会員のテーブル-->
  <div class='row'>
    <div class='col-md-8 offset-md-2 mt-2'>
      <table class="table table-bordered">

        <thead>
          <tr>
            <th class="atora2 text-white">
              会員ID
            </th>

            <td class="haku">
              <%= @customer.id %>
            </td>

            <td></td>
          </tr>

          <tr>
            <th class="atora2 text-white">
              氏名
            </th>

            <td class="haku">
              <%= @customer.full_name %>
            </td>
          </tr>

          <tr>
            <th class="atora2 text-white">
              フリガナ
            </th>

            <td class="haku">
              <%= @customer.full_name_kana %>
            </td>

            <td></td>
          </tr>

          <tr>
            <th class="atora2 text-white">
              郵便番号
            </th>

            <td class="haku">
              <%= @customer.postal_code %>
            </td>

            <td></td>
          </tr>

          <tr>
            <th class="atora2 text-white">
              住所
            </th>

            <td class="haku">
              <%= @customer.address %>
            </td>

            <td></td>
          </tr>

          <tr>
            <th class="atora2 text-white">
              電話番号
            </th>

            <td class="haku">
              <%= @customer.telephone_number %>
            </td>

            <td></td>
          </tr>

          <tr>
            <th class="atora2 text-white">
              メールアドレス
            </th>

            <td class="haku">
              <%= @customer.email %>
            </td>

            <td></td>
          </tr>

          <tr>
            <th class="atora2 text-white">
              会員ステータス
            </th>

            <td class="haku">
              <% if @customer.is_deleted == false %>
                <strong class="text-success">有効</strong>
              <% else %>
                <strong class="text-secondary">退会</strong>
              <% end %>
            </td>

            <td></td>
          </tr>

          <tr>
            <th class="atora2 text-white"></th>
            <td>
              <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: 'btn btn-block btn-success' %>
            </td>

            <td>
              <%= link_to "ランキング情報詳細を見る", admin_ranking_path(@ranking.id), class: 'btn btn-block btn-primary' %>
            </td>
          </tr>
        </thead>

      </table>
    </div>
  </div>

</div>