config/routes.rb
Rails.application.routes.draw do
# 会員用1です。こんな世界にしてみたい。
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

# ゲストログイン専用
  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

# 検索機能
  get "search" => "searches#search"

# 会員用2
scope module: :public do
  root :to =>"homes#top"
  get "about"=>"homes#about"

  resources :ores, only: [:index,:show,:edit]

  get 'customers/my_page' =>"customers#show"
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw'

  post 'rankings/confirm' => 'rankings#confirm'
  get 'rankings/complete' => 'rankings#complete'
  get 'rankings/bookmark' => 'rankings#bookmark'
  get 'rankings/recommend' => 'rankings#recommend'

  resources :rankings, only: [:new,:create,:index,:show] do
    resource :favorites, only: [:create, :destroy]
    resources :stone_comments, only: [:create, :destroy]
  end

  resources :decorations, only: [:index,:edit,:create,:destroy,:update]
end

#管理者専用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  get "admin" => 'admin/homes#top'

  namespace :admin do
    resources :ores

    resources :genres, only: [:index,:create,:edit,:update,:destroy]

    resources :customers, only: [:index,:show,:edit,:update]

    resources :rankings, only: [:show,:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ore.rb
class Ore < ApplicationRecord
    has_many :rankings, dependent: :destroy
    has_many :tagmaps, dependent: :destroy
    has_many :tags, through: :tagmaps
    belongs_to :genre
    has_one_attached :image

  # validatesを後ほど作る。複数か？それとも

  # ジャンル検索のメソッド
  def self.looks(search, word)
    if search == "perfect_match"
     @ore = Ore.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
     @ore = Ore.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
     @ore = Ore.where("name LIKE?", "%#{word}")
    elsif search == "partical_match"
     @ore = Ore.where("name LIKE?", "%#{word}%")
    else
     @ore = Ore.all
    end
  end


  # ↓ここからタグ検索用のメソッド
  def self.ores_search(search)
   Ore.where(['title LIKE ? OR content LIKE ?', "%#{search}%", "%#{search}%"])
  end

  def save_ores(tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    # destroy
    old_tags.each do |old_name|
    self.tags.delete Tag.find_by(tag_name:old_name)
    end

    # create
    new_tags.each do |new_name|
    ore_tag = Tag.find_or_create_by(tag_name:new_name)
    self.tags << ore_tag
    end
  end

end

app/controllers/admin/ores_controller.rb
class Admin::OresController < ApplicationController
  # adminの管理者権限
  before_action :authenticate_admin!

  def index
    @ores = Ore.all
    @ore = Ore.new
  end

  def new
    @ore = Ore.new
  end

  def create
    @ore = Ore.new(ore_params)
    tag_list = params[:ore][:stone].split(',')
    if @ore.save!
       @ore.save_ores(tag_list)
       redirect_to admin_ore_path(@ore.id),notice:'投稿完了しました:)'
    else
       redirect_to admin_ores_path
    end
  end

  def show
    @ore = Ore.find(params[:id])
    @ore_new = Ore.new
  end

  def edit
    @ore = Ore.find(params[:id])
  end

  def update
    @ore = Ore.find(params[:id])
    @ore.update(ore_params)
    redirect_to admin_ore_path(@ore)
  end

  def destroy
    @ore = Ore.find(params[:id])
    @ore.destroy
    redirect_to admin_ores_path
  end

  private

  def ore_params
    params.require(:ore).permit(:stone, :introduction, :is_active, :image, :genre_id)
  end

end

app/helpers/admin/ores_helper.rb
module Admin::OresHelper
end

app/views/admin/ores/edit.html.erb
<div class="container">
  <div class="m-md-2"><br></div>
  <div class="row">

    <h4 class="col-md-2 mx-auto text-center teo">
      <strong>鉱石編集</strong>
    </h4>

    <div class="col-md-8"></div>
  </div>

  <div class="m-md-2"><br></div>

  <%= form_with model: @ore, url: admin_ore_path(@ore) do |f| %>

    <div class="form-group row">
      <div class="col-md-3"></div>

      <div class="col-md-1 text-left">
        <%= f.label :image, '鉱石画像' %>
      </div>

      <div class="col-md-8">
        <%= f.file_field :image, accept: "image/*", required: true %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>

      <div class="col-md-1 text-left">
        <%= f.label :stone, '鉱石名' %>
      </div>

      <div class="col-md-8">
        <%= f.text_field :stone, placeholder: "鉱石名", required: true, size: "44" %>
      </div>
    </div>

   <div class="form-group row">
      <div class="col-md-3"></div>

      <div class="col-md-1 text-left">
        <%= f.label :introduction, '鉱石説明' %>
      </div>

      <div class="col-md-8">
        <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", required: true, size: "46x10" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>

      <div class="col-md-1 text-left">
        <%= f.label :genre_id, 'ジャンル' %>
      </div>

      <div class="col-md-8">
        <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name),prompt: "-- 選択してください --", required: true, class: "w-50" %>
      </div>
    </div>

   <div class="form-group row">
      <div class="col-md-3"></div>

      <div class="col-md-2 text-left">鉱石ステータス</div>

      <div class="col-md-7">
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, '上位' %>

        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, '選外' %>
      </div>
    </div>

    <!--変更を保存ボタン-->
    <div class="row">
      <div class="action center-block mx-auto">
        <%= f.submit '変更を保存', class: "btn btn-success" %>
      </div>
    </div>

  <% end %>

</div>

app/views/admin/ores/index.html.erb
<div class="container">
  <div class="m-md-2"><br></div>
  <div class="row">

    <h4 class="col-md-2 mx-auto text-center teo pikari mb-4">
      <strong>鉱石一覧</strong>
    </h4>

    <!--新規鉱石登録へ-->
    <div class="col-md-5 mx-auto text-right mb-4">
      <%= link_to "+", new_admin_ore_path, class: "h1 text-decoration-none text-dark", 'data-turbolinks': false %>
    </div>
  </div>

  <table class="table table-hover table-bordered">

    <thead class="text-white atora2">

      <tr>
        <th>鉱石ID</th>
        <th>鉱石名</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>

    </thead>

    <tbody class="haku">

      <% @ores.each do |ore| %>

        <tr>
          <td><%= ore.id %></td>
          <td><%= link_to ore.stone, admin_ore_path(ore) %></td>
          <td><%= ore.stone %>
              <%= link_to "削除する", admin_ore_path(ore.id), class: 'btn btn-sm btn-danger offset-md-2', method: :delete %>
          </td>

          <% if ore.is_active == true %>
            <td class="text-success font-weight-bold">上位</td>
          <% else %>
            <td class="text-danger font-weight-bold">選外</td>
          <% end %>

        </tr>

      <% end %>

    </tbody>

  </table>

</div>

app/views/admin/ores/new.html.erb
<div class="container">
  <div class="row">

    <h4 class="col-md-2 mx-auto text-center teo mt-5 mb-4 pikari ">
      <strong>鉱石一覧</strong>
    </h4>

  </div>

  <div class="col-md-6 mx-auto">
    <%= form_with model: @ore, url: admin_ores_path, method: :post do |f| %>

    <div class="form-group row">

      <div class="col-md-3 text-left">
        <%= f.label :image, '鉱石画像' %>
      </div>

      <div class="col-md-9">
        <%= f.file_field :image, accept: "image/*", required: true %>
      </div>
    </div>

    <div class="form-group row">

      <div class="col-md-3 text-left">
        <%= f.label :stone, '鉱石名' %>
      </div>

      <div class="col-md-9">
        <%= f.text_field :stone, placeholder: "鉱石名", required: true, size: "44" %>
      </div>
    </div>

    <div class="form-group row">

      <div class="col-md-3 text-left">
        <%= f.label :introduction, '鉱石説明' %>
      </div>

      <div class="col-md-9">
        <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", required: true, size: "46x10" %>
      </div>
    </div>

    <div class="form-group row">

      <div class="col-md-3 text-left">
        <%= f.label :genre_id, 'ジャンル' %>
      </div>

      <div class="col-md-9">
        <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name),prompt: "-- 選択してください --", required: true, class: "w-50" %>
      </div>
    </div>

    <div class="form-group row">

      <div class="col-md-3 text-left">鉱石ステータス</div>

      <div class="col-md-9">
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, '上位' %>

        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, '選外' %>

      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-3 text-left">タグ</div>

      <div class="col-md-9">
        <%= f.text_field :stone,value: @tag_list, class:"form-control" %>
      </div>

    </div>

    <!--新規登録ボタン-->
    <div class="row">
      <div class="action center-block mx-auto">
      <%= f.submit '新規登録', class: "btn btn-success mb-2" %>
      </div>
    </div>

  <% end %>
  </div>
</div>

app/views/admin/ores/show.html.erb
<div class="container">
 <div class="m-md-2"><br></div>
 <div class="row">

     <h4 class="col-md-2 mx-auto text-center teo pikari">
         <strong>鉱石詳細</strong>
     </h4>

     <div class="col-md-8"></div>
 </div>

 <div class="m-md-2"><br></div>

    <div class="row">

        <div class="col-md-5 mx-auto">
          <%= image_tag @ore.image, size:'300x200' %>
        </div>

        <div class="col-md-7 mx-auto">
            <table class="table table-hover table-bordered">

                <tbody>

                    <tr>
                        <td class="text-white font-weight-bold atora2 doyon">鉱石名</td>
                        <!--半角スペース3つ-->
                        <td>&nbsp;&nbsp;&nbsp;</td>
                        <td class="haku"><%= @ore.stone %></td>
                    </tr>

                    <tr>
                        <td class="text-white font-weight-bold atora2 doyon">鉱石説明</td>
                        <!--半角スペース3つ-->
                        <td>&nbsp;&nbsp;&nbsp;</td>
                        <td class="haku"><%= @ore.introduction %></td>
                    </tr>

                    <tr>
                        <td class="text-white font-weight-bold atora2 doyon">ジャンル</td>
                        <!--半角スペース3つ-->
                        <td>&nbsp;&nbsp;&nbsp;</td>
                        <td class="haku"><%= @ore.genre.name %></td>
                    </tr>

                    <tr>
                        <td class="text-white font-weight-bold atora2 doyon">鉱石ステータス</td>
                        <!--半角スペース3つ-->
                        <td>&nbsp;&nbsp;&nbsp;</td>

                        <% if @ore.is_active == true %>
                            <td class="text-success font-weight-bold haku">上位</td>
                        <% else %>
                            <td class="text-danger haku">選外</td>
                        <% end %>
                    </tr>

                </tbody>

            </table>

          <div class="col-md-3 mx-auto float-left atiti mt-2">
            <%= link_to '編集する',edit_admin_ore_path(@ore), class: 'btn btn-success btn-block mb-3' %>
          </div>

        </div>

    </div>

   <div class="m-md-1"><br></div>

 </div>

</div>