config/routes.rb
Rails.application.routes.draw do
# 会員用1です。こんな世界にしてみたい。
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

# ゲストログイン専用
  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

# 検索機能
  get "search" => "searches#search"

# 会員用2
scope module: :public do
  root :to =>"homes#top"
  get "about"=>"homes#about"

  resources :ores, only: [:index,:show,:edit]

  get 'customers/my_page' =>"customers#show"
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw'

  post 'rankings/confirm' => 'rankings#confirm'
  get 'rankings/complete' => 'rankings#complete'
  get 'rankings/bookmark' => 'rankings#bookmark'
  get 'rankings/recommend' => 'rankings#recommend'

  resources :rankings, only: [:new,:create,:index,:show] do
    resource :favorites, only: [:create, :destroy]
    resources :stone_comments, only: [:create, :destroy]
  end

  resources :decorations, only: [:index,:edit,:create,:destroy,:update]
end

#管理者専用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  get "admin" => 'admin/homes#top'

  namespace :admin do
    resources :ores

    resources :genres, only: [:index,:create,:edit,:update,:destroy]

    resources :customers, only: [:index,:show,:edit,:update]

    resources :rankings, only: [:show,:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ranking.rb
class Ranking < ApplicationRecord

     belongs_to :customer
     belongs_to :ore
     has_many :stone_comments, dependent: :destroy
     has_many :favorites, dependent: :destroy

    def set_date
      created_at.strftime("%Y/%m/%d %H:%M:%S")
    end

    # バリデーションを後々入れるかもしれない

    # favoritesテーブル内に存在するか調べるメソッド
    def favorited_by?(customer)
      favorites.exists?(customer_id: customer.id)
    end

    def full_name
    self.first_name + self.last_name
    end

    enum status: { silver: 0, bronze: 1, gold: 2 }
    enum rank: { rank1: 0, rank2: 1, rank3: 2 }

end

app/controllers/admin/rankings_controller.rb
class Admin::RankingsController < ApplicationController
  # adminの管理者権限
  before_action :authenticate_admin!

  def show
    @ranking = Ranking.find(params[:id])
  end

  def update
    @ranking = Ranking.find(params[:id])
    if @ranking.update(ranking_params)
      @ranking.update_all(rank: 2) if @ranking.rank == "rank3"
    end
      redirect_to admin_ranking_path(@ranking)
  end

  private

  def ranking_params
    params.require(:ranking).permit(:customer_id, :ore, :amulet, :name, :amount, :rank, :status)
  end
end

app/helpers/admin/rankings_helper.rb
module Admin::RankingsHelper
end

app/views/admin/rankings/show.html.erb
<div class="container">
  <div class="m-md-2"><br></div>
  <!--タイトル-->
  <div class="row">

    <h4 class="col-md-2 mx-auto text-center teo">
      <strong>ランキング情報詳細</strong>
    </h4>

    <div class="col-md-8"></div>
  </div>

  <div class="m-md-2"><br></div>

  <!--登録者-->
  <div class="order row">

    <div class="col-md-2 text-left">
      <strong>登録者</strong>
    </div>

    <div class="col-md-10 text-left">
      <%= link_to @ranking.customer.full_name, admin_customer_path(@ranking) %>
    </div>

  </div>

  <!--登録日時-->
  <div class="order row">

    <div class="col-md-2 text-left">
      <strong>登録日時</strong>
    </div>

    <div class="col-md-10 text-left">
      <%= @ranking.created_at.strftime("%Y/%m/%d") %>
    </div>

  </div>

  <!--装飾品-->
  <div class="order row">

    <div class="col-md-2 text-left">
      <strong>装飾品</strong>
    </div>

    <div class="col-md-10 text-left">
      <%= @ranking.amulet %>
    </div>

  </div>

  <!--順位-->
  <div class="order row">

    <div class="col-md-2 text-left">
      <strong>順位</strong>
    </div>

    <div class="col-md-10 text-left">
      <%= @ranking.rank_i18n %>
    </div>

  </div>

  <!--ランキングステータス更新ボタンなど-->
  <%= form_with model: @ranking, url: admin_ranking_path(@ranking), method: :patch do |f| %>
    <div class="order row">

      <div class="col-md-2 text-left">
        <strong>ユーザーへのオススメ度設定</strong>
      </div>

      <div class="col-md-10 text-left">
        <%= f.select :status, Ranking.statuses.keys.map {|k| [I18n.t("enums.ranking.status.#{k}"), k]}, {}, {class: 'form-control seki'} %>
        <%= f.submit '更新',class: "btn btn-success mt-2" %>
      </div>

    </div>

  <% end %>

  <div class="m-md-2"><br></div>

  <div class="row">
    <div class="col-8">

      <table class="table table-hover table-bordered">

        <!--表の見出し-->
        <thead class="text-white atora2">
          <tr>
            <th>鉱石名</th>
            <th>数量</th>
            <th>順位</th>
          </tr>
        </thead>

        <!--下の列3つ-->
        <tbody class="sisyou">

            <tr>
              <td>
               <%= @ranking.ore.stone %>
              </td>

              <td>
                <%= @ranking.amount %>
              </td>

              <td>
                <%= @ranking.rank_i18n %>
              </td>
            </tr>
        </tbody>

      </table>

    </div>

    <!--コメント管理機能-->
    <% if @ranking.stone_comments.present? %>

  <!--コメント投稿後の繰り返し処理-->
  <% @ranking.stone_comments.each do |stone_comment| %>
    <tr>
      <td>
        <%= image_tag stone_comment.customer.get_image(100,100) %>
      </td>

      <td>
        <%= stone_comment.customer.last_name %>
        <%= stone_comment.customer.first_name %>
      </td>

      <td>
        <%= stone_comment.created_at.strftime('%Y/%m/%d') %>
        <%= stone_comment.comment %>
      </td>

        <td>
          <!--publicのpathだが、管理者用にコントローラーを設定している。-->
          <%= link_to "destroy", ranking_stone_comment_path(stone_comment.ranking, stone_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
        </td>

    </tr>
  <% end %>

<% end %>
<!--↑ここまでコメント管理機能-->

  </div>

</div>