config/routes.rb
Rails.application.routes.draw do
# 会員用1です。こんな世界にしてみたい。
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

# ゲストログイン専用
  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

# 検索機能
  get "search" => "searches#search"

# 会員用2
scope module: :public do
  root :to =>"homes#top"
  get "about"=>"homes#about"

  resources :ores, only: [:index,:show,:edit]

  get 'customers/my_page' =>"customers#show"
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw'

  post 'rankings/confirm' => 'rankings#confirm'
  get 'rankings/complete' => 'rankings#complete'
  get 'rankings/bookmark' => 'rankings#bookmark'
  get 'rankings/recommend' => 'rankings#recommend'

  resources :rankings, only: [:new,:create,:index,:show] do
    resource :favorites, only: [:create, :destroy]
    resources :stone_comments, only: [:create, :destroy]
  end

  resources :decorations, only: [:index,:edit,:create,:destroy,:update]
end

#管理者専用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  get "admin" => 'admin/homes#top'

  namespace :admin do
    resources :ores

    resources :genres, only: [:index,:create,:edit,:update,:destroy]

    resources :customers, only: [:index,:show,:edit,:update]

    resources :rankings, only: [:show,:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="ness2 mt-4">
  <div class="container mb-5">
    <div class="row no-gutters">

      <% unless customer_signed_in? || request.path_info == '/admin/sign_in' || admin_signed_in? %>
        <div class='col-md-5 offset-md-5 d-flex align-items-center'>
          <button type="button" class="btn btn-light mt-5">
            <%= link_to 'ゲストログイン（お試し用）', public_guest_sign_in_path, method: :post %>
          </button>
        </div>
      <% end %>

    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="ness">
  <!--顧客側のみのロゴ-->
  <% if customer_signed_in? %>
    <%= link_to root_path, class: "float-left d-inline" do %>
      <%= image_tag "logo.png", size: "110x110" %>
    <% end %>
  <% end %>

  <!--admin側のみのロゴ-->
  <% if admin_signed_in? %>
    <%= link_to admin_path, class: "float-left d-inline" do %>
      <%= image_tag "admin_logo.png", size: "110x110" %>
    <% end %>
  <% end %>

  <div class="container mb-5 d-inline">
    <div class="row">

      <!--customerのログイン-->
      <% if customer_signed_in? %>

        <div class='col-md-12 offset-md-4 d-flex align-items-center'>
          <!--ボタンの右揃え-->
          <div class="text-right">
            <!--ボタン4つ-->
              <%= link_to 'マイページ',customers_my_page_path, class: "text-dark btn btn-light mt-2" %>

              <%= link_to '鉱石一覧',ores_path, class: "text-dark btn btn-light mt-2" %>

              <%= link_to '装飾品一覧',decorations_path, class: "text-dark btn btn-light mt-2" %>

              <%= link_to 'ログアウト',destroy_customer_session_path, method: :delete, class: "text-dark btn btn-light mt-2" %>

          </div>
        </div>
        <!--adminのログイン-->
        <% elsif admin_signed_in? %>
          <div class='col-md-5 offset-md-5 d-flex align-items-center'>
            <!--ボタンの右揃え-->
            <div class="text-right">
              <!--ボタン5つ-->
              <button type="button" class="btn btn-light mt-1">
                <%= link_to 'ランキング情報一覧',admin_path, class: "text-dark" %>
              </button>

              <button type="button" class="btn btn-light mt-1">
                <%= link_to '鉱石一覧',admin_ores_path, class: "text-dark" %>
              </button>

              <button type="button" class="btn btn-light mt-1">
                <%= link_to '会員一覧',admin_customers_path, class: "text-dark" %>
              </button>

              <button type="button" class="btn btn-light mt-1">
                <%= link_to 'ジャンル一覧',admin_genres_path, class: "text-dark" %>
              </button>

             <button type="button" class="btn btn-light mt-1">
                <%= link_to 'ログアウト',destroy_admin_session_path, method: :delete, class: "text-dark" %>
             </button>

            </div>
          </div>
        <!--ログイン前-->
        <% else %>
          <div class='col-md-5 offset-md-5 d-flex align-items-center'>
            <!--ボタンの右揃え-->
            <div class="text-right">
              <!--ボタン4つ-->
              <button type="button" class="btn btn-light mt-2">
                <%= link_to 'About',about_path, class: "text-dark" %>
              </button>

              <button type="button" class="btn btn-light mt-2">
                <%= link_to '鉱石一覧',ores_path, class: "text-dark" %>
              </button>

              <button type="button" class="btn btn-light mt-2">
                <%= link_to '新規登録',new_customer_registration_path, class: "text-dark" %>
              </button>

              <button type="button" class="btn btn-light mt-2">
                <%= link_to 'ログイン',new_customer_session_path, class: "text-dark" %>
              </button>

            </div>
          </div>
      <% end %>

    </div>
  </div>

  <!--検索機能-->
  <% unless admin_signed_in? %>
    <div class="float-right d-inline">
      <%= render "layouts/searcher", { search: @search } %>
    </div>
  <% end %>

</header>

app/views/layouts/_search.html.erb
<div class = "text-left">
  <table class="border border-dark col-10">

    <thead>
      <tr class = "text-center">
        <th class="border-bottom border-dark messi">ジャンル一覧</th>
      </tr>
    </thead>

    </tbody>
      <% genres.each do |genre| %>
        <tr class = "text-center">
          <td class = "text-secondary border-bottom border-dark h-50">
            <%= link_to ores_path(genre_id: genre.id), class: "text-dark" do %>
              <%= genre.name %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>

app/views/layouts/_searcher.html.erb
<!--パスの設定とルーティングの書き方が分かりません。-->
<%= search_form_for @search, url: ores_path do |f| %>
  <%= f.text_field :stone_cont, placeholder: "気になるワードを入力", value: "" %>
  <%= f.submit "検索", name: nil %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kouseki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag(asset_path('favicon.ico')) %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>